// flow-typed signature: be793cdee1a3d5bba5f5502b3e7fd7ba
// flow-typed version: <<STUB>>/react-player-controls_v^1.1.0/flow_v0.111.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-player-controls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-player-controls' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-player-controls/dist/components/Button' {
  declare module.exports: any;
}

declare module 'react-player-controls/dist/components/FormattedTime' {
  declare module.exports: any;
}

declare module 'react-player-controls/dist/components/icons' {
  declare module.exports: any;
}

declare module 'react-player-controls/dist/components/RangeControlOverlay' {
  declare module.exports: any;
}

declare module 'react-player-controls/dist/components/Slider' {
  declare module.exports: any;
}

declare module 'react-player-controls/dist/constants' {
  declare module.exports: any;
}

declare module 'react-player-controls/dist/index' {
  declare module.exports: any;
}

declare module 'react-player-controls/dist/utils' {
  declare module.exports: any;
}

declare module 'react-player-controls/src/components/Button' {
  declare module.exports: any;
}

declare module 'react-player-controls/src/components/FormattedTime' {
  declare module.exports: any;
}

declare module 'react-player-controls/src/components/icons' {
  declare module.exports: any;
}

declare module 'react-player-controls/src/components/RangeControlOverlay' {
  declare module.exports: any;
}

declare module 'react-player-controls/src/components/Slider' {
  declare module.exports: any;
}

declare module 'react-player-controls/src/constants' {
  declare module.exports: any;
}

declare module 'react-player-controls/src/index' {
  declare module.exports: any;
}

declare module 'react-player-controls/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-player-controls/dist/components/Button.js' {
  declare module.exports: $Exports<'react-player-controls/dist/components/Button'>;
}
declare module 'react-player-controls/dist/components/FormattedTime.js' {
  declare module.exports: $Exports<'react-player-controls/dist/components/FormattedTime'>;
}
declare module 'react-player-controls/dist/components/icons.js' {
  declare module.exports: $Exports<'react-player-controls/dist/components/icons'>;
}
declare module 'react-player-controls/dist/components/RangeControlOverlay.js' {
  declare module.exports: $Exports<'react-player-controls/dist/components/RangeControlOverlay'>;
}
declare module 'react-player-controls/dist/components/Slider.js' {
  declare module.exports: $Exports<'react-player-controls/dist/components/Slider'>;
}
declare module 'react-player-controls/dist/constants.js' {
  declare module.exports: $Exports<'react-player-controls/dist/constants'>;
}
declare module 'react-player-controls/dist/index.js' {
  declare module.exports: $Exports<'react-player-controls/dist/index'>;
}
declare module 'react-player-controls/dist/utils.js' {
  declare module.exports: $Exports<'react-player-controls/dist/utils'>;
}
declare module 'react-player-controls/src/components/Button.js' {
  declare module.exports: $Exports<'react-player-controls/src/components/Button'>;
}
declare module 'react-player-controls/src/components/FormattedTime.js' {
  declare module.exports: $Exports<'react-player-controls/src/components/FormattedTime'>;
}
declare module 'react-player-controls/src/components/icons.js' {
  declare module.exports: $Exports<'react-player-controls/src/components/icons'>;
}
declare module 'react-player-controls/src/components/RangeControlOverlay.js' {
  declare module.exports: $Exports<'react-player-controls/src/components/RangeControlOverlay'>;
}
declare module 'react-player-controls/src/components/Slider.js' {
  declare module.exports: $Exports<'react-player-controls/src/components/Slider'>;
}
declare module 'react-player-controls/src/constants.js' {
  declare module.exports: $Exports<'react-player-controls/src/constants'>;
}
declare module 'react-player-controls/src/index.js' {
  declare module.exports: $Exports<'react-player-controls/src/index'>;
}
declare module 'react-player-controls/src/utils.js' {
  declare module.exports: $Exports<'react-player-controls/src/utils'>;
}
