// flow-typed signature: 1f0986ad574019c7c11d39bb07dae0c3
// flow-typed version: <<STUB>>/react-alert_v^5.5.0/flow_v0.111.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-alert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-alert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-alert/dist/cjs/react-alert' {
  declare module.exports: any;
}

declare module 'react-alert/dist/esm/react-alert' {
  declare module.exports: any;
}

declare module 'react-alert/dist/umd/react-alert' {
  declare module.exports: any;
}

declare module 'react-alert/dist/umd/react-alert.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-alert/dist/cjs/react-alert.js' {
  declare module.exports: $Exports<'react-alert/dist/cjs/react-alert'>;
}
declare module 'react-alert/dist/esm/react-alert.js' {
  declare module.exports: $Exports<'react-alert/dist/esm/react-alert'>;
}
declare module 'react-alert/dist/umd/react-alert.js' {
  declare module.exports: $Exports<'react-alert/dist/umd/react-alert'>;
}
declare module 'react-alert/dist/umd/react-alert.min.js' {
  declare module.exports: $Exports<'react-alert/dist/umd/react-alert.min'>;
}
