// flow-typed signature: 5f8eefc76022c6f8ec24d806382f117b
// flow-typed version: <<STUB>>/react-load-script_v^0.0.6/flow_v0.111.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-load-script'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-load-script' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-load-script/lib/index' {
  declare module.exports: any;
}

declare module 'react-load-script/lib/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-load-script/lib/index.js' {
  declare module.exports: $Exports<'react-load-script/lib/index'>;
}
declare module 'react-load-script/lib/index.test.js' {
  declare module.exports: $Exports<'react-load-script/lib/index.test'>;
}
