// flow-typed signature: 17d9b6990de4d4114071748ab3596084
// flow-typed version: <<STUB>>/videojs-http-source-selector_vgit+https://gitlab.com/olaris/videojs-http-source-selector.git/flow_v0.111.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'videojs-http-source-selector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'videojs-http-source-selector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'videojs-http-source-selector/dist/videojs-http-source-selector.cjs' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/dist/videojs-http-source-selector.es' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/dist/videojs-http-source-selector' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/dist/videojs-http-source-selector.min' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/scripts/modules.rollup.config' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/scripts/server' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/scripts/test.rollup.config' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/scripts/umd.rollup.config' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/scripts/version' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/src/components/SourceMenuButton' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/src/components/SourceMenuItem' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/src/plugin' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/test/karma.conf' {
  declare module.exports: any;
}

declare module 'videojs-http-source-selector/test/plugin.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'videojs-http-source-selector/dist/videojs-http-source-selector.cjs.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/dist/videojs-http-source-selector.cjs'>;
}
declare module 'videojs-http-source-selector/dist/videojs-http-source-selector.es.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/dist/videojs-http-source-selector.es'>;
}
declare module 'videojs-http-source-selector/dist/videojs-http-source-selector.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/dist/videojs-http-source-selector'>;
}
declare module 'videojs-http-source-selector/dist/videojs-http-source-selector.min.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/dist/videojs-http-source-selector.min'>;
}
declare module 'videojs-http-source-selector/scripts/modules.rollup.config.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/scripts/modules.rollup.config'>;
}
declare module 'videojs-http-source-selector/scripts/server.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/scripts/server'>;
}
declare module 'videojs-http-source-selector/scripts/test.rollup.config.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/scripts/test.rollup.config'>;
}
declare module 'videojs-http-source-selector/scripts/umd.rollup.config.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/scripts/umd.rollup.config'>;
}
declare module 'videojs-http-source-selector/scripts/version.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/scripts/version'>;
}
declare module 'videojs-http-source-selector/src/components/SourceMenuButton.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/src/components/SourceMenuButton'>;
}
declare module 'videojs-http-source-selector/src/components/SourceMenuItem.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/src/components/SourceMenuItem'>;
}
declare module 'videojs-http-source-selector/src/plugin.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/src/plugin'>;
}
declare module 'videojs-http-source-selector/test/karma.conf.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/test/karma.conf'>;
}
declare module 'videojs-http-source-selector/test/plugin.test.js' {
  declare module.exports: $Exports<'videojs-http-source-selector/test/plugin.test'>;
}
