// flow-typed signature: b8ab28436085aed158e4463017e4cc88
// flow-typed version: <<STUB>>/videojs-overlay_v^2.1.4/flow_v0.111.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'videojs-overlay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'videojs-overlay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'videojs-overlay/dist/videojs-overlay.cjs' {
  declare module.exports: any;
}

declare module 'videojs-overlay/dist/videojs-overlay.es' {
  declare module.exports: any;
}

declare module 'videojs-overlay/dist/videojs-overlay' {
  declare module.exports: any;
}

declare module 'videojs-overlay/dist/videojs-overlay.min' {
  declare module.exports: any;
}

declare module 'videojs-overlay/scripts/karma.conf' {
  declare module.exports: any;
}

declare module 'videojs-overlay/scripts/postcss.config' {
  declare module.exports: any;
}

declare module 'videojs-overlay/scripts/rollup.config' {
  declare module.exports: any;
}

declare module 'videojs-overlay/src/plugin' {
  declare module.exports: any;
}

declare module 'videojs-overlay/test/dist/bundle' {
  declare module.exports: any;
}

declare module 'videojs-overlay/test/plugin.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'videojs-overlay/dist/videojs-overlay.cjs.js' {
  declare module.exports: $Exports<'videojs-overlay/dist/videojs-overlay.cjs'>;
}
declare module 'videojs-overlay/dist/videojs-overlay.es.js' {
  declare module.exports: $Exports<'videojs-overlay/dist/videojs-overlay.es'>;
}
declare module 'videojs-overlay/dist/videojs-overlay.js' {
  declare module.exports: $Exports<'videojs-overlay/dist/videojs-overlay'>;
}
declare module 'videojs-overlay/dist/videojs-overlay.min.js' {
  declare module.exports: $Exports<'videojs-overlay/dist/videojs-overlay.min'>;
}
declare module 'videojs-overlay/scripts/karma.conf.js' {
  declare module.exports: $Exports<'videojs-overlay/scripts/karma.conf'>;
}
declare module 'videojs-overlay/scripts/postcss.config.js' {
  declare module.exports: $Exports<'videojs-overlay/scripts/postcss.config'>;
}
declare module 'videojs-overlay/scripts/rollup.config.js' {
  declare module.exports: $Exports<'videojs-overlay/scripts/rollup.config'>;
}
declare module 'videojs-overlay/src/plugin.js' {
  declare module.exports: $Exports<'videojs-overlay/src/plugin'>;
}
declare module 'videojs-overlay/test/dist/bundle.js' {
  declare module.exports: $Exports<'videojs-overlay/test/dist/bundle'>;
}
declare module 'videojs-overlay/test/plugin.test.js' {
  declare module.exports: $Exports<'videojs-overlay/test/plugin.test'>;
}
