// flow-typed signature: 5cd25c17dde70586b32f415ee76ca9e4
// flow-typed version: <<STUB>>/@videojs/http-streaming_vgit+https://gitlab.com/olaris/videojs-http-streaming.git#olaris/flow_v0.111.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@videojs/http-streaming'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@videojs/http-streaming' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@videojs/http-streaming/dist/videojs-http-streaming.cjs' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/dist/videojs-http-streaming.es' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/dist/videojs-http-streaming' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/dist/videojs-http-streaming.min' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/scripts/clean-tests' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/scripts/manifest-data' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/scripts/netlify' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/scripts/rollup.config' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/scripts/segments-data' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/scripts/server' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/scripts/switcher.rollup.config' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/scripts/test.rollup.config' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/scripts/version' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/scripts/webworker.rollup.config' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/ad-cue-tags' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/bin-utils' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/config' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/dash-playlist-loader' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/decrypter-worker' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/master-playlist-controller' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/media-groups' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/media-segment-request' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/middleware-set-current-time' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/mse/add-text-track-data' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/mse/create-text-tracks-if-necessary' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/mse/html-media-source' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/mse/index' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/mse/remove-cues-from-track' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/mse/transmuxer-worker' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/mse/virtual-source-buffer' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/playback-watcher' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/playlist-loader' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/playlist-selectors' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/playlist' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/ranges' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/reload-source-on-error' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/rendition-mixin' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/resolve-url' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/segment-loader' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/source-updater' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/sync-controller' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/util/buffer' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/util/codecs' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/util/gops' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/util/logger' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/util/noop' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/util/string' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/util/text-tracks' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/util/time' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/videojs-http-streaming' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/vtt-segment-loader' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/src/xhr' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/ad-cue-tags.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/codecs.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/configuration.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/custom-assertions' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/dash-playlist-loader.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/karma.conf' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/loader-common' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/master-playlist-controller.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/media-groups.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/media-segment-request.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/mse/add-text-track-data.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/mse/create-url.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/mse/html.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/mse/index.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/playback-watcher.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/playback.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/playlist-loader.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/playlist-selectors.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/playlist.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/ranges.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/reload-source-on-error.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/rendition-mixin.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/resolve-url.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/sanity.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/segment-loader.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/source-updater.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/sync-controller.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/test-helpers' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/text-tracks.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/util/buffer.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/util/codec-utils.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/util/gops.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/util/string.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/util/time.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/videojs-http-streaming.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/vtt-segment-loader.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/test/xhr.test' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/utils/fixtures/gear4-0.mp4' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/utils/fixtures/gear4-1.mp4' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/utils/stats/stats' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/utils/switcher/aggregate-simulations' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/utils/switcher/display-timeline' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/utils/switcher/fn' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/utils/switcher/network_logs/default' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/utils/switcher/run-simulation' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/utils/switcher/switcher' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/utils/switcher/throttle-server' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/utils/ts-segment-bc' {
  declare module.exports: any;
}

declare module '@videojs/http-streaming/utils/ts-segment' {
  declare module.exports: any;
}

// Filename aliases
declare module '@videojs/http-streaming/dist/videojs-http-streaming.cjs.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/dist/videojs-http-streaming.cjs'>;
}
declare module '@videojs/http-streaming/dist/videojs-http-streaming.es.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/dist/videojs-http-streaming.es'>;
}
declare module '@videojs/http-streaming/dist/videojs-http-streaming.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/dist/videojs-http-streaming'>;
}
declare module '@videojs/http-streaming/dist/videojs-http-streaming.min.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/dist/videojs-http-streaming.min'>;
}
declare module '@videojs/http-streaming/scripts/clean-tests.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/scripts/clean-tests'>;
}
declare module '@videojs/http-streaming/scripts/manifest-data.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/scripts/manifest-data'>;
}
declare module '@videojs/http-streaming/scripts/netlify.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/scripts/netlify'>;
}
declare module '@videojs/http-streaming/scripts/rollup.config.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/scripts/rollup.config'>;
}
declare module '@videojs/http-streaming/scripts/segments-data.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/scripts/segments-data'>;
}
declare module '@videojs/http-streaming/scripts/server.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/scripts/server'>;
}
declare module '@videojs/http-streaming/scripts/switcher.rollup.config.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/scripts/switcher.rollup.config'>;
}
declare module '@videojs/http-streaming/scripts/test.rollup.config.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/scripts/test.rollup.config'>;
}
declare module '@videojs/http-streaming/scripts/version.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/scripts/version'>;
}
declare module '@videojs/http-streaming/scripts/webworker.rollup.config.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/scripts/webworker.rollup.config'>;
}
declare module '@videojs/http-streaming/src/ad-cue-tags.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/ad-cue-tags'>;
}
declare module '@videojs/http-streaming/src/bin-utils.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/bin-utils'>;
}
declare module '@videojs/http-streaming/src/config.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/config'>;
}
declare module '@videojs/http-streaming/src/dash-playlist-loader.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/dash-playlist-loader'>;
}
declare module '@videojs/http-streaming/src/decrypter-worker.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/decrypter-worker'>;
}
declare module '@videojs/http-streaming/src/master-playlist-controller.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/master-playlist-controller'>;
}
declare module '@videojs/http-streaming/src/media-groups.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/media-groups'>;
}
declare module '@videojs/http-streaming/src/media-segment-request.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/media-segment-request'>;
}
declare module '@videojs/http-streaming/src/middleware-set-current-time.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/middleware-set-current-time'>;
}
declare module '@videojs/http-streaming/src/mse/add-text-track-data.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/mse/add-text-track-data'>;
}
declare module '@videojs/http-streaming/src/mse/create-text-tracks-if-necessary.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/mse/create-text-tracks-if-necessary'>;
}
declare module '@videojs/http-streaming/src/mse/html-media-source.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/mse/html-media-source'>;
}
declare module '@videojs/http-streaming/src/mse/index.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/mse/index'>;
}
declare module '@videojs/http-streaming/src/mse/remove-cues-from-track.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/mse/remove-cues-from-track'>;
}
declare module '@videojs/http-streaming/src/mse/transmuxer-worker.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/mse/transmuxer-worker'>;
}
declare module '@videojs/http-streaming/src/mse/virtual-source-buffer.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/mse/virtual-source-buffer'>;
}
declare module '@videojs/http-streaming/src/playback-watcher.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/playback-watcher'>;
}
declare module '@videojs/http-streaming/src/playlist-loader.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/playlist-loader'>;
}
declare module '@videojs/http-streaming/src/playlist-selectors.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/playlist-selectors'>;
}
declare module '@videojs/http-streaming/src/playlist.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/playlist'>;
}
declare module '@videojs/http-streaming/src/ranges.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/ranges'>;
}
declare module '@videojs/http-streaming/src/reload-source-on-error.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/reload-source-on-error'>;
}
declare module '@videojs/http-streaming/src/rendition-mixin.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/rendition-mixin'>;
}
declare module '@videojs/http-streaming/src/resolve-url.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/resolve-url'>;
}
declare module '@videojs/http-streaming/src/segment-loader.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/segment-loader'>;
}
declare module '@videojs/http-streaming/src/source-updater.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/source-updater'>;
}
declare module '@videojs/http-streaming/src/sync-controller.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/sync-controller'>;
}
declare module '@videojs/http-streaming/src/util/buffer.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/util/buffer'>;
}
declare module '@videojs/http-streaming/src/util/codecs.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/util/codecs'>;
}
declare module '@videojs/http-streaming/src/util/gops.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/util/gops'>;
}
declare module '@videojs/http-streaming/src/util/logger.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/util/logger'>;
}
declare module '@videojs/http-streaming/src/util/noop.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/util/noop'>;
}
declare module '@videojs/http-streaming/src/util/string.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/util/string'>;
}
declare module '@videojs/http-streaming/src/util/text-tracks.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/util/text-tracks'>;
}
declare module '@videojs/http-streaming/src/util/time.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/util/time'>;
}
declare module '@videojs/http-streaming/src/videojs-http-streaming.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/videojs-http-streaming'>;
}
declare module '@videojs/http-streaming/src/vtt-segment-loader.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/vtt-segment-loader'>;
}
declare module '@videojs/http-streaming/src/xhr.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/src/xhr'>;
}
declare module '@videojs/http-streaming/test/ad-cue-tags.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/ad-cue-tags.test'>;
}
declare module '@videojs/http-streaming/test/codecs.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/codecs.test'>;
}
declare module '@videojs/http-streaming/test/configuration.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/configuration.test'>;
}
declare module '@videojs/http-streaming/test/custom-assertions.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/custom-assertions'>;
}
declare module '@videojs/http-streaming/test/dash-playlist-loader.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/dash-playlist-loader.test'>;
}
declare module '@videojs/http-streaming/test/karma.conf.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/karma.conf'>;
}
declare module '@videojs/http-streaming/test/loader-common.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/loader-common'>;
}
declare module '@videojs/http-streaming/test/master-playlist-controller.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/master-playlist-controller.test'>;
}
declare module '@videojs/http-streaming/test/media-groups.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/media-groups.test'>;
}
declare module '@videojs/http-streaming/test/media-segment-request.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/media-segment-request.test'>;
}
declare module '@videojs/http-streaming/test/mse/add-text-track-data.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/mse/add-text-track-data.test'>;
}
declare module '@videojs/http-streaming/test/mse/create-url.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/mse/create-url.test'>;
}
declare module '@videojs/http-streaming/test/mse/html.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/mse/html.test'>;
}
declare module '@videojs/http-streaming/test/mse/index.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/mse/index.test'>;
}
declare module '@videojs/http-streaming/test/playback-watcher.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/playback-watcher.test'>;
}
declare module '@videojs/http-streaming/test/playback.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/playback.test'>;
}
declare module '@videojs/http-streaming/test/playlist-loader.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/playlist-loader.test'>;
}
declare module '@videojs/http-streaming/test/playlist-selectors.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/playlist-selectors.test'>;
}
declare module '@videojs/http-streaming/test/playlist.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/playlist.test'>;
}
declare module '@videojs/http-streaming/test/ranges.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/ranges.test'>;
}
declare module '@videojs/http-streaming/test/reload-source-on-error.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/reload-source-on-error.test'>;
}
declare module '@videojs/http-streaming/test/rendition-mixin.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/rendition-mixin.test'>;
}
declare module '@videojs/http-streaming/test/resolve-url.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/resolve-url.test'>;
}
declare module '@videojs/http-streaming/test/sanity.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/sanity.test'>;
}
declare module '@videojs/http-streaming/test/segment-loader.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/segment-loader.test'>;
}
declare module '@videojs/http-streaming/test/source-updater.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/source-updater.test'>;
}
declare module '@videojs/http-streaming/test/sync-controller.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/sync-controller.test'>;
}
declare module '@videojs/http-streaming/test/test-helpers.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/test-helpers'>;
}
declare module '@videojs/http-streaming/test/text-tracks.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/text-tracks.test'>;
}
declare module '@videojs/http-streaming/test/util/buffer.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/util/buffer.test'>;
}
declare module '@videojs/http-streaming/test/util/codec-utils.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/util/codec-utils.test'>;
}
declare module '@videojs/http-streaming/test/util/gops.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/util/gops.test'>;
}
declare module '@videojs/http-streaming/test/util/string.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/util/string.test'>;
}
declare module '@videojs/http-streaming/test/util/time.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/util/time.test'>;
}
declare module '@videojs/http-streaming/test/videojs-http-streaming.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/videojs-http-streaming.test'>;
}
declare module '@videojs/http-streaming/test/vtt-segment-loader.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/vtt-segment-loader.test'>;
}
declare module '@videojs/http-streaming/test/xhr.test.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/test/xhr.test'>;
}
declare module '@videojs/http-streaming/utils/fixtures/gear4-0.mp4.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/utils/fixtures/gear4-0.mp4'>;
}
declare module '@videojs/http-streaming/utils/fixtures/gear4-1.mp4.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/utils/fixtures/gear4-1.mp4'>;
}
declare module '@videojs/http-streaming/utils/stats/stats.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/utils/stats/stats'>;
}
declare module '@videojs/http-streaming/utils/switcher/aggregate-simulations.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/utils/switcher/aggregate-simulations'>;
}
declare module '@videojs/http-streaming/utils/switcher/display-timeline.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/utils/switcher/display-timeline'>;
}
declare module '@videojs/http-streaming/utils/switcher/fn.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/utils/switcher/fn'>;
}
declare module '@videojs/http-streaming/utils/switcher/network_logs/default.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/utils/switcher/network_logs/default'>;
}
declare module '@videojs/http-streaming/utils/switcher/run-simulation.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/utils/switcher/run-simulation'>;
}
declare module '@videojs/http-streaming/utils/switcher/switcher.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/utils/switcher/switcher'>;
}
declare module '@videojs/http-streaming/utils/switcher/throttle-server.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/utils/switcher/throttle-server'>;
}
declare module '@videojs/http-streaming/utils/ts-segment-bc.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/utils/ts-segment-bc'>;
}
declare module '@videojs/http-streaming/utils/ts-segment.js' {
  declare module.exports: $Exports<'@videojs/http-streaming/utils/ts-segment'>;
}
